name: Refresh Single Ticker Data

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker to refresh'
        required: true
        type: string
      triggered_by:
        description: 'User who triggered the refresh'
        required: false
        type: string
        default: 'api'

jobs:
  refresh-ticker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'earnings-tracker/scripts/package-lock.json'
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        # Install Google Chrome Stable
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Install additional dependencies
        sudo apt-get install -y \
          fonts-liberation \
          libu2f-udev \
          libvulkan1 \
          xdg-utils
        echo "Chrome version:"
        google-chrome --version
        echo "Chrome path: $(which google-chrome || which google-chrome-stable)"
    
    - name: Install dependencies
      working-directory: earnings-tracker/scripts
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        echo "Installing npm dependencies (Chrome download disabled)..."
        npm install
        echo "Dependencies installed successfully"
    
    - name: Run scraper for ${{ github.event.inputs.ticker }}
      working-directory: earnings-tracker/scripts
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        PUPPETEER_SKIP_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
        CI: true
      run: |
        echo "Starting refresh for ticker: ${{ github.event.inputs.ticker }}"
        echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
        echo "Chrome available at:"
        which google-chrome || which google-chrome-stable || echo "No Chrome found in PATH"
        echo "Testing Chrome launch..."
        google-chrome --version || echo "Chrome not accessible"
        node scrape-single-stock.js ${{ github.event.inputs.ticker }}
    
    - name: Report status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Successfully refreshed data for ${{ github.event.inputs.ticker }}"
        else
          echo "❌ Failed to refresh data for ${{ github.event.inputs.ticker }}"
        fi