name: Refresh Single Ticker Data

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker to refresh'
        required: true
        type: string
      triggered_by:
        description: 'User who triggered the refresh'
        required: false
        type: string
        default: 'api'

jobs:
  refresh-ticker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'earnings-tracker/scripts/package-lock.json'
    
    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          fonts-liberation \
          libasound2 \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libatspi2.0-0 \
          libcups2 \
          libdbus-1-3 \
          libdrm2 \
          libgbm1 \
          libgtk-3-0 \
          libnspr4 \
          libnss3 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxkbcommon0 \
          libxrandr2 \
          xdg-utils
        echo "Chrome path: $(which chromium-browser || which chromium || which google-chrome || echo 'not found')"
    
    - name: Install dependencies
      working-directory: earnings-tracker/scripts
      env:
        PUPPETEER_SKIP_DOWNLOAD: true
      run: |
        echo "Installing npm dependencies (Chrome download disabled)..."
        npm install
        echo "Dependencies installed successfully"
    
    - name: Run scraper for ${{ github.event.inputs.ticker }}
      working-directory: earnings-tracker/scripts
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        PUPPETEER_SKIP_DOWNLOAD: true
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        CI: true
      run: |
        echo "Starting refresh for ticker: ${{ github.event.inputs.ticker }}"
        echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
        echo "Chrome/Chromium available at:"
        which chromium-browser || which chromium || which google-chrome || echo "No Chrome found in PATH"
        node scrape-single-stock.js ${{ github.event.inputs.ticker }}
    
    - name: Report status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Successfully refreshed data for ${{ github.event.inputs.ticker }}"
        else
          echo "❌ Failed to refresh data for ${{ github.event.inputs.ticker }}"
        fi