name: Refresh Single Ticker Data (Simple)

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: 'Stock ticker to refresh'
        required: true
        type: string
      triggered_by:
        description: 'User who triggered the refresh'
        required: false
        type: string
        default: 'api'

jobs:
  refresh-ticker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install script dependencies
      working-directory: earnings-tracker/scripts
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "Installing dependencies..."
        npm install @supabase/supabase-js dotenv
        echo "Dependencies installed"
    
    - name: Setup Puppeteer
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    
    - name: Install Puppeteer
      working-directory: earnings-tracker/scripts
      run: |
        npm install puppeteer@21.11.0
        echo "Puppeteer installed"
    
    - name: Run scraper for ${{ github.event.inputs.ticker }}
      working-directory: earnings-tracker/scripts
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
      run: |
        echo "Starting refresh for ticker: ${{ github.event.inputs.ticker }}"
        echo "Triggered by: ${{ github.event.inputs.triggered_by }}"
        node scrape-single-stock.js ${{ github.event.inputs.ticker }}
    
    - name: Report status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Successfully refreshed data for ${{ github.event.inputs.ticker }}"
        else
          echo "❌ Failed to refresh data for ${{ github.event.inputs.ticker }}"
        fi